version: '3.8'
services:
  app:
    container_name: app
    environment:
      TZ: "Asia/Tokyo"
      ENV_DIVISION: "LOCAL"
      PHP_ERROR_REPORTING: "E_ALL"
      PHP_DISPLAY_ERRORS: "On"
      PHP_DISPLAY_STARTUP_ERRORS: "On"
      PHP_OPCACHE_ENABLE: 0
      PHP_OPCACHE_ENABLE_CLI: 0
      PHP_XDEBUG_MODE: debug
      PHP_XDEBUG_CLIENT_HOST: "host.docker.internal"
      PHP_XDEBUG_CLIENT_PORT: 9003
      PHP_XDEBUG_IDE_KEY: VSCODE
    build: ./docker/php
    volumes:
      - ./creator:/var/www
      - ./docker/php/dev/php-xdebug.ini:/usr/local/etc/php/conf.d/php-xdebug.ini:ro
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # composer:
  #   image: composer
  #   container_name: composer
  #   command: "composer install"
  #   volumes:
  #     - ./creator:/app
  nginx:
    image: nginx 
    container_name: nginx
    ports:
      - 8086:80 
    volumes:
      - ./creator:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  db:
    image: mysql:8 
    container_name: db
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bcp_creator
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
      LC_ALL: ja_JP.UTF-8
      TZ: 'Asia/Tokyo' 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
## mysql DBの実データをローカルに保存したい場合はこのコメントアウトをオフにしてバイマウントする
#      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 33306:3306
